### ISSUE TITLE
enb does work on linux.

### ISSUE THREAD

**Issue by luke876** [Omni-guides/Skyrim-Wabbajack_Modlist-Linux#2]
I just wanted to make a correction. Downloading enb comes with a windows and linux version. The linux version disables an effect that doesn't work on linux, but it does work.

**Comment by Omni-guides** [comment]
You are absolutely correct. I guess I got focused on simplicity, especially for deck owners. I will amend to be accurate.

Thanks for raising the point.

**Comment by Omni-guides** [comment]
Edited the ENB sections of both Deck and General Linux guides to be more accurate, and include a link to where the Linux version of ENB can be downloaded. 

However, the Linux ENB is outside the scope of this guide, so I have not gone any further than that.

**Comment by alliumm** [comment]
great! you should also move the "If you really want to do so anyway" text below the mv command to avoid confusion.

**Comment by Omni-guides** [comment]
Done :)
